//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//currentLocation
export default {
    GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
    GET_INPUT:"GET_INPUT",
    TOGGLE_SEARCH_RESULT:"TOGGLE_SEARCH_RESULT",
    GET_ADDRESS_PREDICTIONS:"GET_ADDRESS_PREDICTIONS"
};
